version: "3"
services:
  server:
    image: dslist
    restart: always
    ports:
      - "8081:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dslist
    networks:
      - springboot-mysql-net
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:latest
    restart: always
    networks:
      - springboot-mysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=dslist
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
networks:
  springboot-mysql-net: